/*
 * New growth: the leaves a plant pushes, from the day one shows to the day it
 * finishes unfurling.
 *
 * WHY THIS IS NOT A FOURTH CARE KIND. Water, repot and feed are all the same
 * shape - a repeatable instant, with a "last" field and a bounded log, and the
 * only question ever asked of them is "when was the most recent one". A leaf is
 * not an instant, it is an OBJECT with a life: it appears, it takes two or
 * three weeks to open, and until it does it is a thing the user is watching.
 * Several can be open at once, and the interesting question - "how long did
 * that one take?" - needs both ends of the same entity, which a flat list of
 * timestamps cannot express. Modelling it as a care kind would mean two
 * parallel logs that only pair up by accident of ordering.
 *
 * Everything here is PURE, for the reason every other lib/ module is: the
 * screens that use it import React Native and so cannot be tested under bare
 * `node --test`, and the rule about which tap reverses which is exactly the
 * kind of thing that must be tested rather than eyeballed.
 */

/* A stable key for one local calendar day, "2026-09-11" - kept in sync with
 * calendar.ts, which owns the same rule for the month grid. Local accessors
 * throughout: a leaf noted at 1am in Tel Aviv is the previous day in UTC, and
 * the calendar square must match the day the user remembers. */
function localDayKey(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return '';
  const m = `${d.getMonth() + 1}`.padStart(2, '0');
  const day = `${d.getDate()}`.padStart(2, '0');
  return `${d.getFullYear()}-${m}-${day}`;
}

export interface LeafEvent {
  /* Stable across the two taps that make a leaf, so the second one can find
   * the first. Generated by the caller, which owns id generation everywhere
   * else in the app too. */
  id: string;
  /* ISO-8601. The day the user first saw it. */
  emergedAt: string;
  /* ISO-8601, set on the second tap. Absent means the leaf is still opening -
   * which is the state the feature exists to show, not a missing value. */
  maturedAt?: string;
}

/*
 * The same ceiling as the care logs, and for the same reason: the whole library
 * is one JSON blob parsed on every launch, so an unbounded list is a slow leak
 * into the cost of opening the app. Far past any real plant - a monstera pushes
 * maybe a dozen leaves a year.
 */
export const MAX_LEAF_LOG = 500;

function isIso(v: unknown): v is string {
  return typeof v === 'string' && v !== '' && !Number.isNaN(Date.parse(v));
}

export function isLeafEvent(v: unknown): v is LeafEvent {
  if (typeof v !== 'object' || v === null) return false;
  const leaf = v as Record<string, unknown>;
  if (typeof leaf.id !== 'string' || leaf.id === '') return false;
  if (!isIso(leaf.emergedAt)) return false;
  /* Absent is the normal state; present-but-junk is damage and must not reach
   * a calendar as `Invalid Date`. */
  return leaf.maturedAt === undefined || isIso(leaf.maturedAt);
}

/*
 * Clean a stored list into something every reader can walk unguarded.
 *
 * A leaf with no usable emergence is DROPPED - there is no leaf without the day
 * it showed. A bad maturity is treated more gently: junk or a stamp predating
 * its own emergence loses the STAMP and keeps the leaf, because the leaf
 * existing is the user's fact while the impossible ordering is our bug or a
 * clock change, and deleting the record over it would lose more than it fixes.
 */
export function normalizeLeaves(raw: unknown): LeafEvent[] {
  const list = Array.isArray(raw) ? raw : [];
  const seen = new Set<string>();
  const out: LeafEvent[] = [];

  for (const entry of list) {
    if (typeof entry !== 'object' || entry === null) continue;
    const candidate = entry as Record<string, unknown>;
    if (typeof candidate.id !== 'string' || candidate.id === '') continue;
    if (!isIso(candidate.emergedAt)) continue;
    if (seen.has(candidate.id)) continue;
    seen.add(candidate.id);

    const leaf: LeafEvent = { id: candidate.id, emergedAt: candidate.emergedAt };
    if (isIso(candidate.maturedAt) && Date.parse(candidate.maturedAt) >= Date.parse(leaf.emergedAt)) {
      leaf.maturedAt = candidate.maturedAt;
    }
    out.push(leaf);
  }

  /* Newest first, the order every list in this app reads in, and bounded after
   * sorting so the cap drops the OLDEST rather than whatever happened to be
   * stored last. */
  return out.sort((a, b) => Date.parse(b.emergedAt) - Date.parse(a.emergedAt)).slice(0, MAX_LEAF_LOG);
}

/* The first tap: a new leaf is showing. Always a new entry - two leaves opening
 * on the same day is a real thing a plant does, so there is no same-day fold
 * here of the kind the care logs need. */
export function emergeLeaf(leaves: readonly LeafEvent[], id: string, at: number): LeafEvent[] {
  return normalizeLeaves([{ id, emergedAt: new Date(at).toISOString() }, ...leaves]);
}

/*
 * The second tap: that leaf has finished opening.
 *
 * A leaf that is already grown, or one that is not in the list, returns the
 * list UNCHANGED and by reference - the caller checks identity to decide
 * whether there is anything worth persisting, rather than writing storage for
 * a tap that meant nothing.
 *
 * A maturity earlier than the emergence is clamped UP to the emergence instead
 * of being rejected: it can only happen when the device clock moved, and
 * "grown the instant it appeared" is a less confusing record than a tap that
 * silently did nothing.
 */
export function matureLeaf(leaves: readonly LeafEvent[], id: string, at: number): LeafEvent[] {
  const target = leaves.find((leaf) => leaf.id === id);
  if (!target || target.maturedAt !== undefined) return leaves as LeafEvent[];

  const stamp = new Date(at).toISOString();
  const maturedAt = Date.parse(stamp) < Date.parse(target.emergedAt) ? target.emergedAt : stamp;
  return normalizeLeaves(leaves.map((leaf) => (leaf.id === id ? { ...leaf, maturedAt } : leaf)));
}

/*
 * Undo the most recent thing the user logged, whatever it was.
 *
 * "Most recent" is by TIMESTAMP across both ends of every leaf, not by position
 * in the list: marking an old leaf grown is the newest action even though its
 * entry sits at the bottom, and an undo that removed the newest leaf instead
 * would delete a record the user never touched.
 *
 * Undoing a maturity clears the stamp and keeps the leaf - the leaf still
 * exists, it is just not finished after all. Undoing an emergence removes the
 * entry entirely, because a leaf with no emergence is not a leaf.
 */
export function undoLastLeaf(leaves: readonly LeafEvent[]): LeafEvent[] {
  let best: { id: string; at: number; kind: 'emerged' | 'matured' } | undefined;

  for (const leaf of leaves) {
    for (const [kind, iso] of [
      ['emerged', leaf.emergedAt],
      ['matured', leaf.maturedAt],
    ] as const) {
      if (!isIso(iso)) continue;
      const at = Date.parse(iso);
      /* Strictly greater, so a leaf marked grown on the same instant it was
       * logged still undoes the maturity first - the user's last tap. */
      if (!best || at > best.at) best = { id: leaf.id, at, kind };
    }
  }

  if (!best) return leaves as LeafEvent[];
  if (best.kind === 'emerged') return leaves.filter((leaf) => leaf.id !== best!.id);
  return leaves.map((leaf) => {
    if (leaf.id !== best!.id) return leaf;
    const { maturedAt: _dropped, ...rest } = leaf;
    return rest;
  });
}

/* Still opening, newest first. The list the detail screen turns into "mark it
 * grown" buttons. */
export function pendingLeaves(leaves: readonly LeafEvent[]): LeafEvent[] {
  return leaves.filter((leaf) => leaf.maturedAt === undefined);
}

export interface LeafCounts {
  total: number;
  pending: number;
  grown: number;
}

export function leafCounts(leaves: readonly LeafEvent[]): LeafCounts {
  const pending = leaves.filter((leaf) => leaf.maturedAt === undefined).length;
  return { total: leaves.length, pending, grown: leaves.length - pending };
}

/*
 * Whole days between the two ends, or between emergence and now for a leaf
 * still opening. Floored, so a leaf logged this morning reads 0 rather than
 * rounding up to a day that has not happened.
 */
export function leafAgeDays(leaf: LeafEvent, now: number): number {
  const from = Date.parse(leaf.emergedAt);
  if (Number.isNaN(from)) return 0;
  const to = leaf.maturedAt !== undefined ? Date.parse(leaf.maturedAt) : now;
  if (Number.isNaN(to)) return 0;
  return Math.max(0, Math.floor((to - from) / 86_400_000));
}

/*
 * The average a finished leaf took, rounded, or undefined when nothing has
 * finished yet. One number is the whole of what a user wants from the history:
 * "about three weeks" is what tells them whether the one on the plant now is
 * behind schedule.
 */
export function averageGrowthDays(leaves: readonly LeafEvent[]): number | undefined {
  const done = leaves.filter((leaf) => leaf.maturedAt !== undefined);
  if (done.length === 0) return undefined;
  const total = done.reduce((sum, leaf) => sum + leafAgeDays(leaf, 0), 0);
  return Math.round(total / done.length);
}

export interface LeafDays {
  /* Local day keys, matching lib/calendar.ts's `dayKey`. */
  emerged: Set<string>;
  matured: Set<string>;
}

/*
 * The two marker sets the calendar draws. Kept apart rather than merged into
 * one "leaf happened here" set because the whole point of tracking both ends is
 * being able to see them as different events on the grid.
 */
export function leafDays(leaves: readonly LeafEvent[]): LeafDays {
  const emerged = new Set<string>();
  const matured = new Set<string>();
  for (const leaf of leaves) {
    const from = localDayKey(leaf.emergedAt);
    if (from) emerged.add(from);
    if (leaf.maturedAt !== undefined) {
      const to = localDayKey(leaf.maturedAt);
      if (to) matured.add(to);
    }
  }
  return { emerged, matured };
}

/*
 * Both ends as a flat, newest-first list. What the "Recent" strip under the
 * calendar merges with the care entries - a leaf opening is an event in the
 * plant's story in exactly the way a watering is.
 */
export interface LeafStamp {
  id: string;
  at: string;
  stage: 'emerged' | 'matured';
}

export function leafStamps(leaves: readonly LeafEvent[]): LeafStamp[] {
  const out: LeafStamp[] = [];
  for (const leaf of leaves) {
    out.push({ id: leaf.id, at: leaf.emergedAt, stage: 'emerged' });
    if (leaf.maturedAt !== undefined) out.push({ id: leaf.id, at: leaf.maturedAt, stage: 'matured' });
  }
  return out.sort((a, b) => Date.parse(b.at) - Date.parse(a.at));
}
