import type { Copy } from './en';

/*
 * The Hebrew tree.
 *
 * Declared as `Copy`, which is what turns drift into a compile error rather
 * than a string that silently stays English on someone's screen. See the note
 * at the top of en.ts.
 *
 * On number agreement: Hebrew does not say "1 plants", and in the singular it
 * usually drops the numeral altogether - "the saved plant", not "your 1 saved
 * plant". That is why these are functions rather than templates with a
 * placeholder; the rule is written as an ordinary conditional in the language
 * it applies to.
 */
export const he: Copy = {
  language: {
    title: 'שפה',
    english: 'English',
    hebrew: 'עברית',
    relaunchNotice: 'השפה שונתה. סגרו ופתחו מחדש את PlantAI כדי להשלים את השינוי.',
    ok: 'אישור',
    back: 'חזרה',
  },
  watering: {
    everyNDays: (min: number) => `כל ${min} ימים`,
    everyRange: (min: number, max: number) => `כל ${min}-${max} ימים`,
    everyDay: 'כל יום',
    tapToStart: (interval: string) => `${interval} · הקישו כדי להתחיל`,
    overdue: (days: number) => (days === 1 ? 'באיחור של יום' : `באיחור של ${days} ימים`),
    dueNowRange: 'הגיע הזמן - בדקו את האדמה',
    dueToday: 'להשקות היום',
    nextTomorrow: 'ההשקיה הבאה מחר',
    nextInDays: (days: number) =>
      days === 1 ? 'ההשקיה הבאה בעוד יום' : `ההשקיה הבאה בעוד ${days} ימים`,
  },
  care: {
    tapToStart: (interval: string) => `כל ${interval} · הקישו כדי להתחיל`,
    dueNowRepot: 'הגיע הזמן - בדקו את השורשים',
    dueNow: 'הגיע הזמן',
    nextTomorrow: (kind: 'repot' | 'fertilizer') =>
      kind === 'repot' ? 'ההחלפה הבאה מחר' : 'הדישון הבא מחר',
    nextInDays: (kind: 'repot' | 'fertilizer', days: number) =>
      kind === 'repot' ? `ההחלפה הבאה בעוד ${days} ימים` : `הדישון הבא בעוד ${days} ימים`,
    months: (n: number) => (n === 1 ? 'חודש' : `${n} חודשים`),
    weeks: (n: number) => (n === 1 ? 'שבוע' : `${n} שבועות`),
    days: (n: number) => (n === 1 ? 'יום' : `${n} ימים`),
  },
  availability: {
    likely: 'כנראה יש',
    maybe: 'ייתכן שיש',
    unlikely: 'כנראה שאין',
    inStock: (shipsToHome: boolean) =>
      `במלאי עכשיו · ${shipsToHome ? 'משלוח עד הבית' : 'איסוף עצמי'}`,
    notFound: 'לא מצאנו את המוצר',
    estimate: (bandLabel: string, confidence: number) => `${bandLabel} · ${confidence}%`,
    stockUnknown: 'מופיע בקטלוג · המלאי לא צוין',
    unknown: 'זמינות לא ידועה',
    unknownCallToConfirm: 'זמינות לא ידועה - התקשרו לוודא',
  },
  freshness: {
    justNow: 'המלאי נבדק ממש עכשיו',
    minutesAgo: (minutes: number) => `המלאי נבדק לפני ${minutes} דקות`,
    hoursAgo: (hours: number) =>
      hours === 1 ? 'המלאי נבדק לפני שעה' : `המלאי נבדק לפני ${hours} שעות`,
    yesterday: 'המלאי נבדק אתמול',
    daysAgo: (days: number) => `המלאי נבדק לפני ${days} ימים`,
  },
  triage: {
    attention: 'דורשים טיפול',
    watching: 'במעקב',
    healthy: 'בריאים',
  },
  identity: {
    speciesMatch: (percent: number) => `${percent}% התאמה למין`,
    genusMatch: (percent: number) => `${percent}% התאמה לסוג`,
    probably: 'ככל הנראה',
    possibly: 'ייתכן שזה',
    genusLedTitle: 'אנחנו יודעים מהי הקבוצה, אבל לא את המין המדויק',
    genusLedBody: (p: { genus: string; genusPercent: number; plantName: string; percent: number }) =>
      `זהו ${p.genus} (${p.genusPercent}% התאמה). איננו יכולים לקבוע איזה מין בדיוק - ${p.plantName} הוא הקרוב ביותר עם ${p.percent}%. הטיפול המתאים לקבוצה אמין; מה שספציפי למין עשוי שלא להתאים.`,
    moderateTitle: 'איננו בטוחים במין',
    moderateBody: (plantName: string) =>
      `זה נראה כמו ${plantName}, אבל ההתאמה אינה ודאית. ההמלצות שלמטה מניחות שהזיהוי נכון.`,
    lowTitle: 'לא הצלחנו לזהות את הצמח',
    lowBody: (plantName: string) =>
      `${plantName} הוא הניחוש הטוב ביותר שלנו, והוא חלש. התייחסו להמלצות שלמטה כנקודת פתיחה, לא כאבחון. תמונה שבה העלים ממלאים את הפריים, באור יום, בדרך כלל מזהה הרבה יותר טוב.`,
  },
  diagnosis: {
    headerTitle: 'אבחון',
    back: 'חזרה',
    backToHomeA11y: 'חזרה למסך הבית',
    saveA11y: 'שמירה לצמחים שלי',
    savedA11y: 'נשמר לצמחים שלי. הקישו כדי להסיר.',
    saveFailedTitle: 'לא הצלחנו לשמור',
    saveFailedNetwork: 'לא הצלחנו להגיע לחשבון שלכם. בדקו את החיבור ונסו שוב.',
    saveFailedStorage: 'אין מספיק מקום פנוי במכשיר. פנו מקום ונסו שוב.',
    closestSpecies: (name: string) => `המין הקרוב ביותר: ${name}`,
    identityA11y: (parts: {
      prefix: string;
      headline: string;
      genusLabel: string;
      species: string;
      label: string;
      caveat: string;
    }) =>
      [
        parts.prefix,
        `${parts.headline}.`,
        parts.genusLabel ? `${parts.genusLabel}.` : '',
        parts.species ? `המין הקרוב ביותר ${parts.species}, ${parts.label}.` : `${parts.label}.`,
        parts.caveat ? `${parts.caveat}.` : '',
      ]
        .filter(Boolean)
        .join(' '),
    retakeA11y: 'לא הצמח שלכם? צילום מחדש',
    retake: 'לא הצמח שלכם? לצלם מחדש',
    issues: 'בעיות שזוהו',
    treatments: 'תוכנית טיפול',
    urgent: 'דחוף',
    findProduct: (product: string) => `למצוא ${product} בסביבה`,
    findProductA11y: (product: string) => `למצוא ${product} במשתלות בסביבתכם`,
    replaceOr: 'או להחליף בצמח בריא',
    replaceTitle: 'למצוא תחליף בריא',
    replaceDesc: (name: string) =>
      `הצמח הזה פגוע מכדי להציל. אפשר למצוא ${name} זהה ובריא במשתלות בסביבתכם.`,
    delivered: 'משלוח היום',
    pickup: 'איסוף עצמי',
    findNurseriesA11y: 'חיפוש משתלות',
    findDelivery: 'אפשרויות משלוח',
    findNearby: 'משתלות בסביבה',
    scanAnother: 'סריקת צמח נוסף',
  },
  auth: {
    back: 'חזרה',
    email: 'אימייל',
    password: 'סיסמה',
    loginTitle: 'התחברות',
    loginSubtitle: 'גישה לפרופיל ולהגדרות שלכם.',
    loginCta: 'להתחבר',
    loginA11y: 'התחברות',
    forgotPassword: 'שכחתם סיסמה?',
    signupLink: 'הרשמה',
    loginLink: 'התחברות',
    wrongCredentials: 'אימייל או סיסמה שגויים.',
    generic: 'משהו השתבש. נסו שוב.',
    signupTitle: 'יצירת חשבון',
    signupSubtitle: 'לא חובה - האבחון עובד מצוין גם בלי חשבון.',
    signupCta: 'ליצור חשבון',
    signupA11y: 'יצירת חשבון',
    fullName: 'שם מלא',
    username: 'שם משתמש',
    usernameTaken: 'שם המשתמש הזה תפוס.',
    emailTaken: 'כבר קיים חשבון עם האימייל הזה.',
    signupFailed: 'לא הצלחנו ליצור את החשבון שלכם.',
    resetTitle: 'איפוס סיסמה',
    resetCta: 'שליחת קישור לאיפוס',
    resetA11y: 'שליחת קישור לאיפוס',
    newPassword: 'סיסמה חדשה',
    currentPassword: 'סיסמה נוכחית',
    setPasswordTitle: 'הגדרת סיסמה חדשה',
    setPasswordSubtitle: 'בחרו סיסמה חדשה לחשבון שלכם.',
    setPasswordCta: 'להגדיר סיסמה',
    setPasswordA11y: 'הגדרת סיסמה חדשה',
    passwordUpdated: 'הסיסמה שלכם עודכנה.',
    goToLogin: 'להתחבר',
    goToLoginA11y: 'מעבר להתחברות',
    linkExpired: 'קישור האיפוס פג או שכבר נעשה בו שימוש. בקשו קישור חדש.',
    changePasswordTitle: 'שינוי סיסמה',
    changePasswordCta: 'לעדכן סיסמה',
    changePasswordA11y: 'עדכון סיסמה',
    currentPasswordWrong: 'הסיסמה הנוכחית שגויה.',
  },
  settings: {
    title: 'הגדרות',
    back: 'חזרה',
    loginPrompt: 'התחברות / הרשמה',
    loginPromptA11y: 'התחברות או הרשמה',
    loggedOutBlurb:
      'צרו חשבון כדי לשמור את הפרופיל שלכם ולנהל את הפרטים. האבחון עובד מצוין גם בלי חשבון.',
    deviceSection: 'במכשיר הזה',
    profileSettings: 'הגדרות פרופיל',
    fullName: 'שם מלא',
    username: 'שם משתמש',
    emailAddress: 'כתובת אימייל',
    bio: 'אודות',
    notifications: 'התראות',
    manageAccount: 'ניהול חשבון',
    save: 'שמירה',
    saveFailed: 'לא הצלחנו לשמור. נסו שוב.',
    usernameTaken: 'שם המשתמש הזה תפוס.',
    changePassword: 'שינוי סיסמה',
    logOut: 'התנתקות',
    deleteAccount: 'מחיקת חשבון',
    deleting: 'מוחקים…',
    deleteTitle: 'למחוק את החשבון?',
    deleteBody:
      'הפעולה תמחק לצמיתות את החשבון שלכם ואת כל הצמחים במכשיר הזה, כולל אלה שנשמרו לפני שנרשמתם. אין תקופת חסד ואין דרך לבטל.',
    deleteFailedTitle: 'המחיקה נכשלה',
    deleteFailedBody: 'משהו השתבש במחיקת החשבון שלכם. נסו שוב.',
    cancel: 'ביטול',
    pushNotifications: 'התראות דחיפה',
    wateringReminder: 'תזכורת השקיה',
    pushOffNote:
      'התראות דחיפה כבויות ברמת המערכת. הפעילו אותן בהגדרות iOS כדי לקבל תזכורות השקיה.',
  },
  onboarding: {
    skip: 'דילוג',
    skipA11y: 'דילוג על ההיכרות ומעבר לאפליקציה',
    namePrompt: 'שלום,\nאיך נקרא לכם?',
    namePlaceholder: 'השם שלכם',
    nameA11y: 'השם שלכם, לא חובה',
    continue: 'המשך',
    notNow: 'לא עכשיו',
    notNowNameA11y: 'להמשיך בלי למסור שם',
    next: 'הבא',
    getStarted: 'מתחילים',
    cameraTitle: (name: string) => (name ? `עוד דבר אחד, ${name}` : 'עוד דבר אחד'),
    cameraBlurb:
      'אבחון מתחיל בתמונה של הצמח שלכם, ולכן PlantAI צריך גישה למצלמה. התמונות משמשות לאבחון ונשארות עם הצמח ברשימה שלכם.',
    allowCamera: 'לאשר מצלמה',
    waiting: 'רגע…',
    notNowCameraA11y: 'להמשיך בינתיים בלי גישה למצלמה',
  },
  addPlant: {
    close: 'סגירה',
    title: 'הוספת צמח',
    photo: 'תמונה',
    photoHint: 'לא חובה. אפשר להוסיף אחר כך.',
    removePhoto: 'הסרת התמונה',
    camera: 'מצלמה',
    library: 'גלריה',
    takePhoto: 'צילום תמונה',
    takeDifferent: 'צילום תמונה אחרת',
    choosePhoto: 'בחירת תמונה מהגלריה',
    chooseDifferent: 'בחירת תמונה אחרת',
    photoDenied:
      'ל-PlantAI אין עדיין גישה לתמונות שלכם. אשרו גישה בהגדרות, או הוסיפו את הצמח בלי תמונה וצרפו אחת מאוחר יותר.',
    cameraDenied:
      'ל-PlantAI אין עדיין גישה למצלמה. אשרו גישה בהגדרות, או בחרו תמונה שכבר צילמתם.',
    species: 'מין',
    chooseSpecies: 'בחירת מין',
    speciesChosenA11y: (name: string, scientific: string) =>
      `מין, ${name}, ${scientific}. שינוי המין`,
    nickname: 'כינוי',
    nicknameHint: 'לא חובה. שימושי כשיש לכם שלושה מאותו מין.',
    nicknamePlaceholder: 'ברטה הגדולה',
    nicknameA11y: 'כינוי לצמח',
    save: 'הוספת צמח',
    saveHint: 'בחרו מין קודם',
    saveFailedTitle: 'לא הצלחנו לשמור',
    saveFailedNetwork: 'לא הצלחנו להגיע לחשבון שלכם. בדקו את החיבור ונסו שוב.',
    saveFailedStorage: 'אין מספיק מקום פנוי במכשיר. פנו מקום ונסו שוב.',
  },
  editPlant: {
    close: 'סגירה',
    title: 'עריכת צמח',
    subtitle: (name: string) => `עריכת ${name}`,
    photo: 'תמונה',
    photoHint: 'אפשר להחליף את התמונה או להשאיר אותה כמו שהיא.',
    camera: 'מצלמה',
    library: 'גלריה',
    takePhoto: 'צילום תמונה חדשה',
    choosePhoto: 'בחירת תמונה מהגלריה',
    noPhotoYet: 'אין עדיין תמונה',
    photoDenied:
      'אין ל-PlantAI גישה לתמונות. אפשרו גישה בהגדרות, או השאירו את התמונה הנוכחית.',
    cameraDenied:
      'אין ל-PlantAI גישה למצלמה. אפשרו גישה בהגדרות, או בחרו תמונה שכבר צילמתם.',
    nickname: 'כינוי',
    nicknameHint: 'השאירו ריק כדי לחזור לשם המין.',
    nicknamePlaceholder: 'ברטה הגדולה',
    nicknameA11y: 'כינוי לצמח',
    save: 'שמירת שינויים',
    saving: 'שומר...',
    saveHintUnchanged: 'אין עדיין מה לשמור',
    saveFailedTitle: 'לא הצלחנו לשמור',
    saveFailedNetwork: 'לא הצלחנו להגיע לחשבון. בדקו את החיבור ונסו שוב.',
    saveFailedStorage: 'אין מספיק מקום פנוי במכשיר. פנו מקום ונסו שוב.',
    saveFailedMissing: 'הצמח הזה כבר לא נמצא בספרייה שלכם.',
    editA11y: (name: string) => `עריכת ${name}`,
  },
  bulkCare: {
    diagnoseAll: 'אבחון הכול',
    waterAll: 'השקיית הכול',
    diagnoseConfirmTitle: 'לאבחן את כל הצמחים?',
    diagnoseConfirmBody: (n: number, skipped: number) =>
      skipped === 0
        ? `נבדקים ${n} צמחים שמעולם לא אובחנו. הפעולה רצה ברקע ולוקחת בערך דקה לכל חמישה צמחים.`
        : `נבדקים ${n} צמחים שמעולם לא אובחנו. ל-${skipped} נוספים אין תמונה, ולכן אי אפשר לבדוק אותם. הפעולה רצה ברקע ולוקחת בערך דקה לכל חמישה צמחים.`,
    diagnoseNothingTitle: 'אין מה לאבחן',
    diagnoseNothingBody: 'כל צמח שיש לו תמונה כבר נבדק.',
    diagnoseNoPhotos: (n: number) =>
      `ל-${n} צמחים אין עדיין תמונה, ולכן אין מה לשלוח. אפשר להוסיף תמונה במסך העריכה של הצמח.`,
    diagnoseRunning: (done: number, total: number) => `מאבחן ${done} מתוך ${total}`,
    diagnoseDone: (done: number) => `אובחנו ${done} צמחים`,
    diagnoseDoneWithFailures: (done: number, failed: number) =>
      `אובחנו ${done}, ${failed} לא נבדקו`,
    diagnoseDoneSkipped: (skipped: number) => `${skipped} דולגו, אין תמונה`,
    cancel: 'עצירה',
    dismiss: 'סגירה',
    waterConfirmTitle: 'להשקות את הצמחים שצריכים?',
    waterConfirmBody: (n: number) =>
      n === 1
        ? 'הצמח יסומן כמושקה עכשיו והלוח שלו יתחיל מחדש.'
        : `כל ${n} הצמחים יסומנו כמושקים עכשיו, כולל אלה שעוד לא הגיע זמנם, והלוחות שלהם יתחילו מחדש.`,
    waterNothingTitle: 'אין עדיין צמחים',
    waterNothingBody: 'הוסיפו צמח והוא יסומן כמושקה.',
    waterDone: (n: number) => `הושקו ${n} צמחים`,
    waterFailed: 'חלק מהצמחים לא עודכנו. בדקו את החיבור ונסו שוב.',
    confirm: 'בצע',
    cancelAction: 'ביטול',
    a11yDiagnoseAll: 'אבחון כל הצמחים שלא אובחנו',
    a11yWaterAll: 'סימון כל הצמחים כמושקים',
  },
  speciesPicker: {
    title: 'בחירת מין',
    close: 'סגירת בוחר המינים',
    placeholder: 'מונסטרה, Thai Constellation, הויה',
    searchA11y: 'חיפוש מינים',
    clear: 'ניקוי החיפוש',
    rowA11y: (name: string, scientific: string) => `${name}, ${scientific}`,
    emptyTitle: (query: string) => `לא נמצאו מינים שתואמים "${query}"`,
    emptyBody:
      'נסו רק את שם הסוג - "אלוקזיה", "הויה", "מונסטרה" - או איות קצר יותר, ואז עיינו ברשימה.',
  },
  plantSearch: {
    title: 'חיפוש צמח',
    subtitle: 'חפשו משתלות בסביבתכם לצמח שאתם רוצים לקנות, והשוו מחירים.',
    placeholder: 'אלוקזיה ריגל שילד',
    inputA11y: 'הצמח שאתם מחפשים',
    clear: 'ניקוי החיפוש',
    deliver: 'משלוח',
    pickUp: 'איסוף',
    submit: 'חיפוש משתלות',
    fromYourPlants: 'מהצמחים שלכם',
    suggestionA11y: (name: string) => `חיפוש משתלות עבור ${name}`,
    note: 'החיפוש קורא את אתר כל משתלה בזמן אמת, ולכן הוא יכול לקחת כדקה.',
  },
  statusView: {
    a11y: (title: string, body: string) => `${title}. ${body}`,
  },
  nurseries: {
    unreachableTitle: 'לא הצלחנו להגיע לשירות המשתלות',
    unreachableBody: 'החיפוש לא חזר. אין שום בעיה בצמח שלכם או במיקום שלכם.',
    timeoutTitle: 'החיפוש ארך יותר מדי זמן',
    timeoutBody: 'בדיקת מלאי בזמן אמת בכמה משתלות יכולה לחרוג מהמגבלה שלנו. ניסיון נוסף בדרך כלל עובד.',
    back: 'חזרה',
    countNearby: (n: number) => (n === 1 ? 'משתלה אחת בסביבה' : `${n} משתלות בסביבה`),
    searching: 'מחפשים…',
    searchFailed: 'החיפוש נכשל',
    showMap: 'הצגת מפה',
    showList: 'הצגת רשימה',
    refresh: 'רענון',
    refreshA11y: 'בדיקת המלאי מחדש עכשיו',
    deliverToday: 'משלוח היום',
    pickUp: 'איסוף עצמי',
    searchingTitle: 'מחפשים משתלות בסביבה',
    searchingBody: (plantName: string) =>
      `מאתרים חנויות ברדיוס 10 ק"מ ובודקים מלאי בזמן אמת עבור ${plantName}. זה יכול לקחת 30–60 שניות.`,
    tryAgain: 'לנסות שוב',
    backToHome: 'חזרה למסך הבית',
    emptyTitle: 'לא נמצאו משתלות בסביבה',
    emptyBody: (plantName: string) =>
      `אף חנות ברדיוס 10 ק"מ לא החזירה ${plantName} במלאי. המלאי משתנה לעיתים קרובות, אז שווה לבדוק שוב מאוחר יותר.`,
    searchAgain: 'לחפש שוב',
    diagnoseAnother: 'לאבחן צמח אחר',
    diagnoseAnotherCta: 'אבחון צמח נוסף',
    reviews: (n: number) => `(${n} ביקורות)`,
    inStock: 'במלאי',
    seePrice: 'לצפייה במחיר',
    call: 'התקשרו',
    callA11y: 'התקשרות למשתלה',
    directions: 'הוראות הגעה',
    order: 'להזמין',
    unavailable: 'לא זמין',
    visitStore: 'לבקר בחנות',
    noContact: 'אין אתר או מספר טלפון זמין למשתלה הזו.',
    pillA11y: (text: string, detail: string) => `${text}. ${detail}`,
    pillHint: 'מציג למה',
    mapCallout: (distance: string, price: string) => `${distance}${price ? ` · ${price} · במלאי` : ''}`,
  },
  camera: {
    notAPlantTitle: 'לא מצאנו צמח בתמונה הזו',
    notAPlantBody: 'כוונו את המצלמה לעלים, לגבעולים או לפרחים, מקרוב מספיק כדי למלא את רוב הפריים.',
    unsupportedTitle: 'לא הצלחנו לקרוא את התמונה',
    unsupportedBody:
      'הקובץ הזה בפורמט שאנחנו לא יודעים לפתוח. תמונה שצולמה במצלמה, או JPEG או PNG מהגלריה, תעבוד.',
    tooLargeTitle: 'התמונה הזו גדולה מדי לשליחה',
    tooLargeBody: (size: string, limit: string) =>
      `התמונה במשקל ${size} והמגבלה היא ${limit}. צלמו את התמונה במצלמה במקום - התמונות האלה דחוסות ותמיד נכנסות.`,
    unavailableTitle: 'האבחון אינו זמין',
    unavailableBody: 'הגרסה הזו לא מחוברת לשירות זיהוי צמחים. אין שום בעיה בתמונה או בצמח שלכם.',
    failedTitle: 'לא הצלחנו לסיים את האבחון',
    failedBody: 'שירות הצמחים לא ענה. התמונה שלכם בסדר גמור - זו תקלה אצלנו.',
    captureFailedTitle: 'המצלמה לא צילמה את זה',
    captureFailedBody: 'משהו הפריע לצילום. נסו שוב, או בחרו תמונה קיימת מהגלריה.',
    photoPermissionTitle: 'PlantAI צריך גישה לתמונות שלכם',
    photoPermissionBody: 'אשרו גישה לתמונות בהגדרות כדי לבחור תמונה שכבר צילמתם.',
    tryAgain: 'לנסות שוב',
    takeAnother: 'לצלם תמונה אחרת',
    backToHome: 'חזרה למסך הבית',
    permissionTitle: 'נדרשת גישה למצלמה',
    permissionDesc: 'PlantAI צריך את המצלמה שלכם כדי לאבחן בעיות בריאות בצמחים.',
    allowCamera: 'לאשר מצלמה',
    allowCameraA11y: 'אישור גישה למצלמה',
    orGallery: 'או לבחור מהגלריה',
    close: 'סגירה',
    closeCamera: 'סגירת המצלמה',
    scanTitle: 'סריקת צמח',
    flipCamera: 'החלפת מצלמה',
    hint: 'מרכזו את הצמח בפריים',
    gallery: 'גלריה',
    pickFromGallery: 'בחירה מהגלריה',
    takePhoto: 'צילום',
    analyzingTitle: 'מנתחים את הצמח שלכם',
    analyzingDesc: 'אנחנו בוחנים את הסימפטומים,\nמזהים את המין ואת המצב...',
  },
  careHistory: {
    water: {
      short: 'השקיה',
      title: 'היסטוריית השקיה',
      empty: 'עוד לא תועדו השקיות - הקישו על "להשקות עכשיו" במסך הצמח כדי להתחיל.',
      logged: (n: number) => (n === 1 ? 'תועדה השקיה אחת' : `תועדו ${n} השקיות`),
      noneThisMonth: 'לא תועדו השקיות החודש',
    },
    repot: {
      short: 'עציץ',
      title: 'היסטוריית החלפות עציץ',
      empty: 'עוד לא תועדו החלפות עציץ - הקישו על "להחליף עכשיו" במסך הצמח כדי להתחיל.',
      logged: (n: number) => (n === 1 ? 'תועדה החלפה אחת' : `תועדו ${n} החלפות`),
      noneThisMonth: 'לא תועדו החלפות החודש',
    },
    fertilizer: {
      short: 'דישון',
      title: 'היסטוריית דישון',
      empty: 'עוד לא תועדו דישונים - הקישו על "לדשן עכשיו" במסך הצמח כדי להתחיל.',
      logged: (n: number) => (n === 1 ? 'תועד דישון אחד' : `תועדו ${n} דישונים`),
      noneThisMonth: 'לא תועדו דישונים החודש',
    },
    allTitle: 'היסטוריית טיפול',
    allEmpty: 'עוד לא תועד דבר - השקו, החליפו עציץ או דשנו כדי להתחיל.',
    allLogged: (n: number) => (n === 1 ? 'תועד טיפול אחד' : `תועדו ${n} טיפולים`),
    allNoneThisMonth: 'לא תועד דבר החודש',
    daysOfCare: (n: number) => (n === 1 ? 'יום אחד של טיפול החודש' : `${n} ימי טיפול החודש`),
    filterAll: 'הכל',
    missingTitle: 'הצמח הזה כבר לא שמור',
    goBack: 'חזרה',
    unnamed: 'צמח ללא שם',
    prevMonth: 'החודש הקודם',
    nextMonth: 'החודש הבא',
    nextDue: 'הטיפול הבא',
    recent: 'אחרונים',
    dayA11y: (date: string, done: string, due: string) => `${date}${done}${due}`,
    /* No lowercasing - Hebrew has no letter case. */
    doneSuffix: (kind: string) => `, ${kind} בוצע`,
    dueSuffix: (kind: string) => `, ${kind} נדרש`,
  },
  plantDetail: {
    missingTitle: 'הצמח הזה כבר לא שמור',
    backToPlants: 'חזרה לצמחים שלי',
    backLabel: 'הצמחים שלי',
    removeA11y: 'הסרת הצמח',
    undiagnosed: 'עוד לא בדקתם את הצמח הזה.',
    checkIt: 'לבדוק',
    checkA11y: (name: string) => `בדיקת ${name} עם המצלמה`,
    issues: 'בעיות שזוהו',
    treatments: 'תוכנית טיפול',
    urgent: 'דחוף',
    findProduct: (product: string) => `למצוא ${product} בסביבה`,
    findProductA11y: (product: string) => `למצוא ${product} במשתלות בסביבתכם`,
    careSchedule: 'לוח טיפול',
    findAtNursery: 'למצוא את הצמח במשתלה',
    findingNurseries: 'מחפשים משתלות...',
    findAtNurseryA11y: (name: string) => `למצוא משתלות שמוכרות ${name}`,
    replacementTitle: 'למצוא תחליף בריא',
    replacementNote: (name: string) =>
      `הצמח הזה פגוע מכדי להציל. אפשר למצוא ${name} בריא בסביבתכם.`,
    findNearby: 'למצוא משתלות בסביבה',
    findNearbyA11y: (name: string) => `למצוא ${name} במשתלות בסביבתכם`,
    savedOn: (date: string) => `נשמר ב-${date}`,
    removeTitle: 'להסיר את הצמח?',
    removeBody: (name: string) => `${name} יוסר מרשימת הצמחים שלכם.`,
    cancel: 'ביטול',
    remove: 'הסרה',
    failNotFound: 'הצמח הזה כבר לא שמור.',
    failNetwork: 'לא הצלחנו להגיע לחשבון שלכם. בדקו את החיבור ונסו שוב.',
    failStorage: 'אין מספיק מקום פנוי במכשיר, ולכן שום דבר לא נשמר.',
    saveFailedTitle: 'לא הצלחנו לשמור',
    saveFailedStorage: 'אין מספיק מקום פנוי במכשיר, ולכן מצע הגידול לא נשמר.',
    logFailedTitle: 'לא הצלחנו לתעד',
    waterFailedStorage: 'אין מספיק מקום פנוי במכשיר, ולכן ההשקיה לא נשמרה.',
    removeFailedTitle: 'לא הצלחנו להסיר',
    removeFailedStorage: 'אין מספיק מקום פנוי במכשיר.',
  },
  soilMedia: {
    potting_mix: { label: 'תערובת שתילה', description: 'אדמה רגילה לצמחי בית על בסיס כבול' },
    aroid_mix: { label: 'תערובת לארואידים', description: 'קליפות עץ, פרלית וקוקוס, מנקזת היטב' },
    leca: { label: 'לקה', description: 'כדורי חרס עם מאגר מים' },
    pon: { label: 'פון', description: 'פומיס, זאוליט ולבה עם דשן בשחרור איטי' },
    sphagnum: { label: 'ספגנום', description: 'טחב סיבי שמחזיק הרבה מים' },
    bark: { label: 'קליפות לסחלבים', description: 'קליפות גסות, מאווררת מאוד, מתייבשת מהר' },
    perlite_mix: { label: 'עתיר פרלית', description: 'רובה פרלית, כמעט הידרופוני' },
    water: { label: 'מים', description: 'השרשה או גידול במים בלבד' },
  },
  carePlan: {
    fallbackTitle: 'טיפול',
    title: (genus: string, medium: string) => `${genus} ב${medium}`,
    noteSpecific: 'נכתב עבור הצמח הזה במצע הזה.',
    noteFallback: 'מתוך האבחון, שלא ידע במה הצמח שתול.',
    light: 'אור',
    humidity: 'לחות',
    soil: 'מצע',
    water: 'מים',
    rowA11y: (label: string, text: string) => `${label}: ${text}`,
    warnA11y: (warning: string) => `שימו לב: ${warning}`,
  },
  soilCard: {
    title: 'מצע גידול',
    empty: 'בחרו במה הצמח הזה שתול.',
    optionA11y: (label: string, description: string) => `${label}. ${description}`,
  },
  features: {
    scan: {
      title: 'צילום ואבחון',
      desc: 'הבינה המלאכותית מזהה מיד מה מציק לצמח',
      blurb:
        'כוונו את המצלמה לצמח שנראה לא טוב. תוך שניות תדעו מה המין, מה הבעיה ואיך לטפל בה.',
    },
    track: {
      title: 'מעקב והשקיה',
      desc: 'לוח השקיה שמותאם לכל צמח ששמרתם',
      blurb:
        'כל צמח שתשמרו מקבל תוכנית טיפול וקצב השקיה, עם תזכורת כדי שלא תצטרכו לנחש.',
    },
    replace: {
      title: 'מציאת תחליף',
      desc: 'איתור צמחים בריאים במשתלות בסביבתכם',
      blurb:
        'כשאי אפשר להציל צמח, נמצא לכם אחד בריא במשתלה קרובה - במשלוח או לאיסוף עצמי.',
    },
  },
  portfolio: {
    brand: 'PlantAI',
    greetingNamed: (name: string) => `הצמחים של ${name}`,
    helloNamed: (name: string) => `שלום, ${name}`,
    greetingAnonymous: 'דוקטור צמחים',
    settingsA11y: 'הגדרות חשבון',
    title: 'הצמחים שלי',
    filterAll: 'הכל',
    filterNeedsCare: 'זקוקים לטיפול',
    filterDiagnosed: 'אובחנו',
    filterCount: (label: string, n: number): string => `${label} (${n})`,
    filterAllA11y: 'הצגת כל הצמחים',
    filterNeedsCareA11y: 'הצגת הצמחים שהטיפול בהם באיחור או להיום בלבד',
    filterDiagnosedA11y: 'הצגת הצמחים שאובחנו בלבד',
    dueThisWeek: 'לטיפול השבוע',
    dueMore: (n: number) => `ועוד ${n} ברשימה למטה`,
    noneNeedCare: 'אין משימות כרגע. כל הצמחים בזמן.',
    noneDiagnosed: 'אף אחד מהצמחים שלכם לא אובחן עדיין. סרקו אחד כדי לראות מה הוא צריך.',
    warnFutureTitle: 'נשמר בגרסה חדשה יותר',
    warnFutureText: 'עדכנו את PlantAI כדי לראות שוב את הרשימה. שום דבר לא נמחק.',
    warnUnreadableTitle: 'חלק מהצמחים השמורים לא נקראו',
    warnUnreadableText: 'המידע שלכם הוזז הצידה, לא נמחק. צמחים חדשים נשמרים כרגיל.',
    diagnoseAnother: 'אבחון צמח נוסף',
    diagnoseAnotherA11y: 'אבחון צמח נוסף - פתיחת המצלמה',
    diagnoseMine: 'אבחון הצמח שלי',
    diagnoseMineA11y: 'אבחון הצמח שלי - פתיחת המצלמה',
    addPlant: 'הוספת צמח',
    addPlantA11y: 'הוספת צמח שכבר יש לכם',
    addOwned: 'הוספת צמח שכבר יש לי',
    addOwnedA11y: 'הוספת צמח שכבר יש לכם, בלי תמונה',
    heroTitle: 'הצמח שלכם\nלא מרגיש טוב?',
    heroSub: 'צלמו תמונה. קבלו אבחון תוך שניות.\nונמצא תחליף בריא אם צריך.',
    howItWorks: 'איך זה עובד',
    bottomNote: 'אנחנו מאבחנים מעל 1000 מיני צמחים · מהר ובדיוק',
  },
  schedule: {
    today: 'היום',
    tomorrow: 'מחר',
    overdue: 'באיחור',
    inDays: (days: number): string => `בעוד ${days} ימים`,
    every: (interval: string): string => `כל ${interval}`,
    none: 'לא נקבע',
  },
  tabs: {
    home: 'בית',
    portfolio: 'הצמחים שלי',
    scan: 'סריקה',
    find: 'חיפוש',
  },
  home: {
    greeting: {
      morning: 'בוקר טוב',
      afternoon: 'צהריים טובים',
      evening: 'ערב טוב',
    },
    greetingWithName: (greeting: string, name: string) => `${greeting}, ${name}`,
    heroEyebrow: 'הגינה שלך במבט אחד',
    heroTitle: 'שמרו על הצמחים\nפורחים היום.',
    heroEmptyTitle: 'התחילו את הגינה\nעם תמונה אחת.',
    heroCta: 'אבחון צמח',
    plantCount: (n: number) => (n === 1 ? 'צמח אחד' : `${n} צמחים`),
    tasksTitle: 'משימות קרובות',
    tasksSeeAll: 'הצגת הכול',
    tasksEmpty: 'אין משימות השבוע. הצמחים שלך מסודרים.',
    taskOthers: (n: number) => (n === 1 ? 'ועוד אחד' : `ועוד ${n}`),
    taskKind: {
      water: 'השקיית צמחים',
      fertilizer: 'דישון',
      repot: 'החלפת עציץ',
    },
    plantsTitle: 'הצמחים שלי',
    plantsSeeAll: 'לתיק הצמחים',
    needsCare: (n: number) => (n === 1 ? 'זקוק לטיפול קטן' : 'זקוקים לטיפול קטן'),
    allHealthy: 'הכול במצב טוב',
    emptyStrip: 'עוד אין צמחים. אבחנו אחד כדי להתחיל.',
    a11yHero: 'אבחון צמח באמצעות המצלמה',
    a11yTask: (kind: string, plants: string, when: string) => `${kind}, ${plants}, ${when}`,
  },
  relativeDay: {
    today: 'היום',
    yesterday: 'אתמול',
    daysAgo: (n: number) => `לפני ${n} ימים`,
    weeksAgo: (n: number) => (n === 1 ? 'לפני שבוע' : `לפני ${n} שבועות`),
    yearsAgo: (n: number) => (n === 1 ? 'לפני שנה' : `לפני ${n} שנים`),
  },
  plantCard: {
    needsWatering: 'זקוק להשקיה',
    diagnosedBadge: 'אובחן',
    a11y: (p: {
      name: string;
      secondary: string;
      conditionLabel: string;
      when: string;
      watering: string;
    }) =>
      `${p.name}${p.secondary ? `, ${p.secondary}` : ''}` +
      (p.conditionLabel ? `, אובחן ${p.conditionLabel}` : ', לא אובחן') +
      `, נשמר ${p.when}` +
      (p.watering ? `, השקיה ${p.watering}` : ''),
  },
  scheduleCard: {
    water: {
      title: 'השקיה',
      action: 'להשקות עכשיו',
      start: 'השקיתי היום',
      done: 'הושקה',
    },
    fertilizer: {
      title: 'דישון',
      action: 'לדשן עכשיו',
      start: 'דישנתי היום',
      done: 'דושן',
    },
    repot: {
      title: 'החלפת עציץ',
      action: 'להחליף עכשיו',
      start: 'החלפתי עציץ היום',
      done: 'הוחלף',
    },
    history: 'היסטוריה',
    /* No lowercasing: Hebrew has no letter case, so the English helper would
     * be a no-op here and reads as a copied line rather than a written one. */
    historyA11y: (title: string) => `היסטוריית ${title}`,
    noSchedule: 'אין לוח זמנים עדיין',
    settledA11y: (done: string, label: string) => `${done}. ${label}`,
    actionA11y: (title: string, action: string, label: string) =>
      `${title}: ${action}.${label ? ` ${label}` : ''}`,
    earlyHint: (title: string) => `הקישו הקשה כפולה והחזיקו כדי לתעד ${title} מוקדם`,
  },
  importBanner: {
    title: (n: number) =>
      n === 1 ? 'לייבא את הצמח השמור שלך?' : `לייבא את ${n} הצמחים השמורים שלך?`,
    sub: 'הם ילוו אותך לכל מכשיר שתתחברו ממנו.',
    partial: (ok: number, failed: number) => `${ok} יובאו, ${failed} נכשלו - הקישו לניסיון נוסף.`,
    importAction: 'ייבוא',
    importA11y: 'ייבוא הצמחים השמורים',
    dismissA11y: 'לא עכשיו',
  },
};
